version: "3.8"
services:
  srs:
    image: ghcr.io/pibbletv/srs:latest
    container_name: pibbletv-srs
    ports:
      - "10080:10080/udp"
    volumes:
      - hls_data:/usr/local/srs/objs/nginx/html/hls

  nginx:
    image: ghcr.io/pibbletv/nginx:latest
    container_name: pibbletv-nginx
    ports:
      - "8080:80"
    volumes:
      - hls_data:/usr/local/srs/objs/nginx/html/hls

volumes:
  hls_data:
