services:
  srs:
    image: ghcr.io/pibbletv/pibbletv-srs:latest
    container_name: SRS
    ports:
      - "10080:10080/udp"
    expose:
      - "10080"
    volumes:
      - hls-data:/usr/local/srs/objs/nginx/html/hls/live

  nginx:
    image: ghcr.io/pibbletv/pibbletv-nginx:latest
    container_name: NGINX
    ports:
      - "80:80"
    volumes:
      - nginx-claim0:/usr/share/nginx/html:ro
      - nginx-claim1:/etc/nginx/nginx.conf:ro
      - hls-data:/usr/local/srs/objs/nginx/html/hls/live:ro
