apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pibbletv-ingress-api
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-port-in-redirects: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - local.167.99.36.185.nip.io
      secretName: pibbletv-tls-api
  rules:
    - host: local.167.99.36.185.nip.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8078
