apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pibbletv-ingress-api
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - gateway.24.144.77.108.nip.io
      secretName: pibbletv-tls-api
  rules:
    - host: gateway.24.144.77.108.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8078
