apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim0
  namespace: default
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi