apiVersion: v1
data:
  nginx.conf: "worker_processes  1;\n\nevents {\n    worker_connections  10000;\n}\n\nhttp {\n   server {\n        listen 80;\n    \n        include       mime.types;\n        default_type  application/octet-stream;\n        \n        root /usr/share/nginx/html;\n        index index.html;\n\n        location /auth/ {\n            proxy_pass http://localhost:8080/auth/;\n            proxy_set_header Host $host;\n            proxy_set_header X-Real-IP $remote_addr;\n            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n            proxy_set_header X-Forwarded-Proto $scheme;\n        }\n\n        location / {\n            try_files $uri $uri/ /index.html;\n\n            add_header Access-Control-Allow-Origin *;\n        }\n\n        location /hls/live/ {\n            alias /usr/local/srs/objs/nginx/html/hls/live/; \n            types {\n                application/vnd.apple.mpegurl m3u8;\n                video/mp2t ts;\n            }\n            add_header Cache-Control no-cache;\n            add_header Access-Control-Allow-Origin *;\n            add_header Pragma no-cache;\n            add_header Expires 0;\n        }\n    }\n}"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
  name: nginx-cm1
