name: Publish Docker image

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Install and build application
        run: |
          npm install
          npm run build

      - name: Build NGINX and SRS images
        run: |
          docker build -f SRS.Dockerfile -t ghcr.io/pibbletv/pibbletv-srs:latest .
          docker build -f NGINX.Dockerfile -t ghcr.io/pibbletv/pibbletv-nginx:latest .

      - name: Push Docker images to GHCR
        run: |
          docker push ghcr.io/pibbletv/pibbletv-srs:latest
          docker push ghcr.io/pibbletv/pibbletv-nginx:latest

      - name: Test pulling images from GHCR
        run: |
          docker pull ghcr.io/pibbletv/pibbletv-srs:latest
          docker pull ghcr.io/pibbletv/pibbletv-nginx:latest
